pipeline {
    agent any

    stages {
        stage('Prepare') {
            agent any

            steps {
                checkout scm
            }

            post {

                success {
                    echo 'prepare success'
                }

                always {
                    echo 'done prepare'
                }

                cleanup {
                    echo 'after all other post conditions'
                }
            }
        }

        stage('build gradle') {
            
            steps {
                dir('server/groute/') {
                    sh  'chmod +x gradlew; ./gradlew build'


                    sh 'ls -al ./build'
                }
            }
            post {
                success {
                    echo 'gradle build success'
                }

                failure {
                    echo 'gradle build failed'
                }
            }
        }

        stage('Docker build') {
            
            agent any
            steps {
                dir('server/groute/') {
                    sh 'docker build --build-arg JAR_FILE=build/libs/groute-0.0.1-SNAPSHOT.jar -t springboot-gorute-image:latest .'
                }
            }
        }
        stage('Docker run') {
            agent any
            steps {
                sh 'docker ps -f name=springboot-gorute-image -q | xargs --no-run-if-empty docker container stop'
                sh 'docker container ls -a -fname=sbor_dev -q | xargs -r docker container rm'
                sh 'docker images --no-trunc --all --quiet --filter="dangling=true" | xargs --no-run-if-empty docker rmi'
                sh 'docker run -d --name springboot-gorute-image -p 8888:8888 springboot-gorute-image:latest'
            }
        }
    }
}
